### PR TITLE
D3-559| make action usable from PR workflows

### PR DESCRIPTION
**Pull request by renefritze**
This composite action reproduces https://github.com/arup-group/oasys-combined/blob/develop/.github/workflows/branch-jira-key.yml which would in turn just call this action.

### CODE REVIEW

**Comment by renefritze** [comment]
This should have a workflow to test itself -> back to draft.

**Comment by renefritze** [comment]
Test workflow needs a JIRA secret set up to work.

**Comment by renefritze** [comment]
> Test workflow needs a JIRA secret set up to work.

That's now done thanks to @MJCramp 

"Local" test of the action now also works and I've added a readme

**Comment by renefritze** [comment]
Pinging @nathanrobertsarup @MJCramp @hariKallubhavi @mgjc75 for reviews

**Review by MJCramp — APPROVED** [review]

**Pull request merged**
